apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- externaldns-package-install.yaml
secretGenerator:
- name: externaldns-packages-values
  namespace: packages
  files:
  - externaldns-data-values.yaml
  type: Opaque
  options:
    annotations:
      tkg.tanzu.vmware.com/tanzu-package: externaldns-packages
